apiVersion: v1
kind: Service
metadata:
  name: hello-eks
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-eks
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
