replicaCount: 2

image:
  repository: "{{ .Values.image.repository }}"
  tag: "{{ .Values.image.tag }}"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
